import { chromium } from "playwright";
const [,, out, base = "https://gapzero-rose.vercel.app"] = process.argv;
const b = await chromium.launch();
const page = await b.newPage({ viewport: { width: 1440, height: 900 } });
await page.context().addCookies([{ name: "gz_intro_done", value: "1", url: base }]); // old "seen it" cookie must not skip the intro
await page.goto(base + "/", { waitUntil: "networkidle" });
await page.waitForTimeout(2000);
await page.getByText("THE PROBLEM", { exact: false }).first().waitFor({ timeout: 10000 });
console.log("opened on the intro:", page.url());
await page.screenshot({ path: `${out}/prod-intro.png` });
await page.getByRole("button", { name: /How GapZero fixes it/ }).click();
await page.getByRole("button", { name: /Enter the command center/ }).click();
await page.waitForURL(base + "/start", { timeout: 15000 });
await page.getByText("Choose who you are").waitFor({ timeout: 15000 });
await page.getByRole("button", { name: /Continue as refill nurse/ }).click();
await page.waitForURL(/\/queue/, { timeout: 15000 });
await page.locator(".driver-popover").waitFor({ timeout: 15000 });
await page.screenshot({ path: `${out}/prod-tour.png` });
console.log("flow ok:", page.url());
await b.close();
