// Handwritten photo: on-device OCR first, then AI vision, then extract and review.
import { chromium } from "playwright";
const [,, base = "http://localhost:3000", out] = process.argv;
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1440, height: 1000 } });
await ctx.addCookies([{ name: "gz_user", value: "usr_nair", url: base }, { name: "gz_intro_done", value: "1", url: base }]);
await ctx.addInitScript(() => ["queue", "intake", "refill"].forEach((t) => localStorage.setItem(`gz_tour_${t}`, "1")));
const page = await ctx.newPage();
page.on("pageerror", (e) => console.log("PAGE ERROR:", e.message));
await page.goto(base + "/intake", { waitUntil: "networkidle" });
let t = Date.now();
await page.getByRole("button", { name: /Handwritten form/ }).click();
await page.getByText(/ from refill-handwritten-photo\.jpg/).waitFor({ timeout: 90000 });
console.log(`on-device OCR: ${((Date.now() - t) / 1000).toFixed(1)}s |`, await page.getByText(/ from refill-handwritten-photo\.jpg/).innerText());
console.log("  OCR text:", JSON.stringify((await page.locator('[data-tour="fax-text"]').inputValue()).slice(0, 160)));
if (out) await page.screenshot({ path: `${out}/vision-before.png` });
t = Date.now();
await page.getByRole("button", { name: /Read with AI vision/ }).first().click();
await page.getByText(/Read with AI vision from/).waitFor({ timeout: 90000 });
const text = await page.locator('[data-tour="fax-text"]').inputValue();
console.log(`AI vision: ${((Date.now() - t) / 1000).toFixed(1)}s`);
console.log("  vision text:", JSON.stringify(text.slice(0, 400)));
if (out) await page.screenshot({ path: `${out}/vision-after.png` });
t = Date.now();
await page.getByRole("button", { name: /Extract and triage/ }).click();
await page.waitForURL(/\/refills\//, { timeout: 60000 });
await page.getByText("Where this refill stands").waitFor({ timeout: 60000 });
const body = await page.locator("body").innerText();
console.log(`extract: ${((Date.now() - t) / 1000).toFixed(1)}s`);
console.log("  matched Aisha:", body.includes("Aisha Patel"), "| flagged for review:", body.includes("Review extraction and match patient"));
console.log("  where it stands:", (body.match(/WHERE THIS REFILL STANDS\s*\n+([^\n]+)/i) || [])[1]);
if (out) await page.screenshot({ path: `${out}/vision-result.png`, fullPage: true });
await b.close();
